export const FANTASTIC_TOWN_WIDTH_VW = 420;
export const ENCHANTED_FOREST_WIDTH_VW = 420;
export const ENCHANTED_FOREST_START_VW = FANTASTIC_TOWN_WIDTH_VW;
export const CASTLE_WALLS_START_VW = FANTASTIC_TOWN_WIDTH_VW + ENCHANTED_FOREST_WIDTH_VW;

const ORIGINAL_WORLD_WIDTH_VW = 800;
const ORIGINAL_WORLD_TRAVEL_VW = 700;

export const WORLD_WIDTH_VW = ORIGINAL_WORLD_WIDTH_VW + CASTLE_WALLS_START_VW;
export const WORLD_TRAVEL_VW = ORIGINAL_WORLD_TRAVEL_VW + CASTLE_WALLS_START_VW;
